[tool.poetry]
name = "NuestroEntorno"
version = "1.0.0"
description = "My personal project to the world"
authors = ["Th3-Butl3r <github-outsider.unknowing582@passinbox.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pre-commit = "^2.20.0"
flask = "^2.3.2"
python-dotenv = "^1.0.0"
folium = "^0.14.0"
pydantic = "^2.1.1"
pydantic-settings = "^2.0.2"
pyjwt = "^2.8.0"
loguru = "^0.7.3"
supabase = "^2.31.0"
gunicorn = "^26.0.0"
sentry-sdk = "^2.63.0"


[tool.poetry.group.dev.dependencies]
pudb = ">=2024.1"
pytest = "^9.0.3"
pytest-asyncio = "^1.4.0"
pytest-cov = "^7.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
